Forward function update
UBC-MDS/feature-selection-r pull request #28
Opened 2020-03-08 01:43 UTC by vcuspinera

Hi guys, send you my function, but I still have some part to do. I will update it for the Milestone 3

2020-03-11 23:25 UTC, ryanhomer commented
@vcuspinera Please run `devtools::check()` (Build/Check Package) and fix errors and warnings.

2020-03-12 04:07 UTC, jackyho112 requested changes
A bunch of concerns. Again, don't need to fix all of them. Do what you can. If some are too much to change, let me know and it's ok.

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +    stop("Expected a 'data.frame' object for `data`.")
Should probably distinguish that from the warning about X. Also, can't y just be a vector?

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +    stop("min_features should be a positive number.")
```suggestion
    stop("min_features should be more than zero.")
```

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +  scores_fn <- c()#Inf
What does the comment here mean?

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +  # The algorithm
No need for this comment.

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +  repeat{ #for (j in 1:max_features){
What's this comment?

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +    if (length(ftr_selection) >= 1){
Combine the two conditions and use `&`

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +  flag_keep_running = TRUE
Why do you need two flags? It is quite confusing. Doesn't `flag_keep_running = TRUE` mean `flag_stop_running = FALSE` inherently? When is it not the case?

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +    if (length(ftr_selection) >= max_features){
Redundancy because you have checked that condition right above?

2020-03-12 04:07 UTC, jackyho112 commented on R/forward_selection.R
> +  repeat{ #for (j in 1:max_features){
Also, a `while` loop wouldn't work here? It's hard to read when the `break` condition is hidden in the loop block.

2020-03-12 04:07 UTC, jackyho112 commented on tests/testthat/test-forward_select.R
> +  # X and y are Dataframes
A lot of the test cases below should be separate and outside of the relevant feature test.

2020-03-12 04:07 UTC, jackyho112 commented on tests/testthat/test-forward_select.R
> +  testthat::expect_gt(length(simulated_annealing(scorer, X, y)), 0)
What's this doing here?

2020-03-13 07:31 UTC, vcuspinera commented on R/forward_selection.R
> +    stop("Expected a 'data.frame' object for `data`.")
I separate the information of 'X' from 'y', and in this case the algorithm needs data frames for both `X` and `y`.

2020-03-13 07:35 UTC, vcuspinera commented on R/forward_selection.R
> +  scores_fn <- c()#Inf
infinite; I used it for a previous version of the function but doesn't make sense anymore, so I just erase it.

2020-03-13 19:30 UTC, jackyho112 approved these changes
Looks good!

2020-03-13 19:31 UTC, merged